# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(blank=True, max_length=100)),
                ('market', models.CharField(blank=True, max_length=100)),
                ('gain_value', models.IntegerField(blank=True, null=True)),
                ('sell_value', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
