# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_auto_20171220_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='Images/None/No-image.jpg', upload_to='Image/'),
        ),
    ]
